{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = "typhon" %}
#{% set version = data['version'] %}
{% set version = "0.11.0dev" %}
{% set dev_url = "https://github.com/atmtools/typhon" %}

package:
  name: {{ name|lower }}
  version:  {{ version }}

source:
  # url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # url: "https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  # url: https://github.com/atmtools/typhon/releases/download/{{ version }}/typhon-{{ version }}.tar.gz
  git_url: {{ dev_url }}.git
  git_depth: 1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=3.4
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - typhon

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  license_file: LICENSE
  summary: {{ data['description'] }}

extra:
  recipe-maintainers:
    - olemke
